version: '3.8'

services:
  backend:
    image: trends-backend:latest
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: trends-frontend:latest
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production

networks:
  default:
    driver: bridge